// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;
public class AmazonloginTest {
	

	public static void main(String[] args) 
	{
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\mohan\\Downloads\\Downloaded program files\\BrowserDrivers\\chromedriver.exe");
		ChromeDriver driver = new ChromeDriver();
    
	driver.get("https://www.amazon.in/");
    driver.manage().window().setSize(new Dimension(1050, 652));
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
    
    driver.findElement(By.cssSelector("#nav-signin-tooltip .nav-action-inner")).click();
    driver.findElement(By.id("ap_email")).sendKeys("mohanadesi@gmail.com");
    //driver.findElement(By.cssSelector(".a-button-inner > #continue")).click();
    driver.findElement(By.cssSelector("input#continue")).click();
    driver.findElement(By.id("ap_password")).sendKeys("s@thy@1840");
    driver.findElement(By.id("signInSubmit")).click();
    {
      WebElement element = driver.findElement(By.id("signInSubmit"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
   
  }
  

 }

